if(NOT DEFINED CLI)
    message(FATAL_ERROR "CLI is required")
endif()

function(run_compute expected_result expected_pattern)
    execute_process(COMMAND "${CLI}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT "${result}" STREQUAL "${expected_result}" OR
       NOT "${output}${error}" MATCHES "${expected_pattern}")
        message(FATAL_ERROR "Compute CLI failed: ${ARGN}\nexit=${result}\n${output}${error}")
    endif()
endfunction()

execute_process(COMMAND "${CLI}" devices
    RESULT_VARIABLE result OUTPUT_VARIABLE capabilities ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT capabilities MATCHES "Default policy: GPU required")
    message(FATAL_ERROR "Device discovery failed: ${capabilities}${error}")
endif()

run_compute(2 "compute-argument" devices --device cpu)
run_compute(2 "compute-argument" compute --device)
run_compute(2 "compute-argument" compute --device unknown)
run_compute(2 "compute-argument" compute --device cpu --device cpu)
run_compute(2 "compute-argument" compute --device-index -1)
run_compute(2 "compute-argument" compute --device-index 99999999999999999999999)
run_compute(2 "compute-argument" compute --unexpected true)
run_compute(2 "compute-argument" compute --precision)
run_compute(2 "compute-argument" compute --precision tf32)
run_compute(2 "compute-argument" compute --precision fp16 --precision fp16)
run_compute(2 "coreml-argument" neural-compute)
run_compute(2 "coreml-argument" neural-compute --model)
run_compute(2 "coreml-argument" neural-compute --model unused.mlmodelc --iterations 0)
run_compute(2 "coreml-argument" neural-compute --model unused.mlmodelc --compute-units cuda)
run_compute(2 "coreml-argument" neural-compute --model unused.mlmodelc --model unused.mlmodelc)
run_compute(2 "coreml-argument" neural-compute --model unused.mlmodelc --allow-cpu-plan --allow-cpu-plan)
run_compute(2 "compute-argument" compute --cpu-share)
run_compute(2 "compute-argument" compute --cpu-share -0.1)
run_compute(2 "compute-argument" compute --cpu-share 1)
run_compute(2 "compute-argument" compute --cpu-share nan)
run_compute(2 "compute-argument" compute --cpu-share 0.2 --cpu-share 0.3)
run_compute(2 "compute-argument" compute --weight-storage disk)
run_compute(2 "compute-argument" compute --gpu-weight-mib 1)
run_compute(2 "compute-argument" compute --weight-storage ram --gpu-weight-mib 0)
run_compute(2 "compute-argument" compute --weight-storage ram --gpu-weight-mib 9999999999999999999)

if(capabilities MATCHES "MLX: available" OR capabilities MATCHES "CPU \\(LibTorch\\): available")
    run_compute(0 "Device: cpu:0" compute --device cpu)
    run_compute(0 "bias -> \\[64,128\\]" compute --device cpu)
    run_compute(6 "compute-unavailable" compute --device cpu --device-index 99)
    run_compute(2 "CPU sharing requires" compute --device cpu --cpu-share 0.25)
    run_compute(0 "CPU output features: 128" compute --device cpu --weight-storage ram)
    run_compute(2 "compute-argument" compute --device cpu --precision fp16)
else()
    run_compute(6 "compute-unavailable" compute --device cpu)
endif()

if(capabilities MATCHES "Metal: available" OR capabilities MATCHES "CUDA: available" OR
   capabilities MATCHES "ROCm \\(AMD\\): available")
    run_compute(0 "Device: (metal|cuda|rocm):0" compute)
    run_compute(0 "CPU output features: 32" compute --cpu-share 0.25)
    run_compute(0 "RAM weight bytes: 131584" compute --cpu-share 0.25 --weight-storage ram
        --gpu-weight-mib 1)
    run_compute(0 "CPU output features: 0" compute --weight-storage ram)
    run_compute(0 "GPU precision: fp16" compute --precision fp16)
    run_compute(0 "GPU precision: fp16" compute --precision fp16 --cpu-share 0.25 --weight-storage ram)
    if(capabilities MATCHES "Metal: available" OR capabilities MATCHES "BF16 Tensor eligibility: yes")
        run_compute(0 "GPU precision: bf16" compute --precision bf16 --cpu-share 0.25 --weight-storage ram)
    endif()
else()
    run_compute(6 "compute-unavailable" compute)
endif()

if(NOT capabilities MATCHES "ROCm \\(AMD\\): (available|unavailable)" OR
   NOT capabilities MATCHES "LibTorch HIP build: (yes|no)")
    message(FATAL_ERROR "AMD discovery is missing: ${capabilities}")
endif()
if(capabilities MATCHES "ROCm \\(AMD\\): available")
    run_compute(0 "Device: rocm:0" compute --device rocm)
    run_compute(0 "ROCm dispatch: LibTorch/HIP" compute --device rocm --cpu-share 0.25 --weight-storage ram)
    run_compute(6 "compute-unavailable" compute --device rocm --device-index 9999999)
else()
    run_compute(6 "ROCm requires" compute --device rocm)
endif()

if(NOT capabilities MATCHES "Core ML: (available|unavailable)" OR
   NOT capabilities MATCHES "Apple Neural Engine: (available|unavailable|unknown)" OR
   NOT capabilities MATCHES "Tensor Cores \\(CUDA\\): (available|unavailable|supported|unsupported|unknown)")
    message(FATAL_ERROR "Neural/Tensor hardware discovery is missing: ${capabilities}")
endif()
if(capabilities MATCHES "CUDA: unavailable")
    run_compute(6 "compute-unavailable" compute --device cuda)
endif()
if(capabilities MATCHES "Metal: unavailable")
    run_compute(6 "compute-unavailable" compute --device metal)
endif()
