"""Explicit CPU text encoding before Diffusers installs accelerator/offload hooks."""

from __future__ import annotations

from dataclasses import dataclass
from itertools import chain
from typing import Any

from presets import PipelinePreset


@dataclass(frozen=True)
class CpuConditioning:
    tensors: dict[str, Any]
    metadata: dict[str, Any]

    def for_device(self, device: str, dtype: Any) -> dict[str, Any]:
        # FLUX does not move user-provided embeddings internally. Explicitly move
        # all four SDXL conditioning tensors as well, including pooled negatives.
        return {
            name: None if tensor is None else tensor.to(device=device, dtype=dtype)
            for name, tensor in self.tensors.items()
        }


def encode_cpu_prompt(
    pipeline: Any, preset: PipelinePreset, args: Any, torch: Any
) -> CpuConditioning:
    encoders = [
        (name, getattr(pipeline, name, None))
        for name, _ in preset.expected_components
        if name in ("text_encoder", "text_encoder_2")
    ]
    for name, encoder in encoders:
        if encoder is None:
            raise RuntimeError(f"CPU conditioning requires {name}.")
        if getattr(encoder, "_hf_hook", None) is not None or encoder.device.type == "meta":
            raise RuntimeError("CPU conditioning must run before accelerator/offload hooks.")

    original_storage = []
    for _, encoder in encoders:
        dtype = encoder.dtype
        # PEFT adapters and some buffers can have a different storage dtype
        # from the base encoder. Retain those tensors, avoiding a lossy
        # float32 -> float16 -> float32 round trip during restoration.
        mixed_parameters = {
            name: tensor.detach().to(device="cpu")
            for name, tensor in encoder.named_parameters() if tensor.dtype != dtype
        }
        mixed_buffers = {
            name: tensor.detach().to(device="cpu")
            for name, tensor in encoder.named_buffers() if tensor.dtype != dtype
        }
        original_storage.append((encoder, dtype, mixed_parameters, mixed_buffers))
    cpu_dtype = getattr(torch, preset.runtime.cpu_dtype)
    try:
        for name, encoder in encoders:
            encoder.to(device="cpu", dtype=cpu_dtype)
            if any(tensor.device.type != "cpu"
                   for tensor in chain(encoder.parameters(), encoder.buffers())):
                raise RuntimeError(f"{name} did not move entirely to the CPU.")

        arguments: dict[str, Any] = {
            "prompt": args.prompt,
            "device": "cpu",
            "num_images_per_prompt": 1,
        }
        if preset.runtime.passes_negative_prompt:
            arguments["negative_prompt"] = args.negative_prompt
            arguments["do_classifier_free_guidance"] = args.guidance_scale > 1.0
        if preset.runtime.max_sequence_length is not None:
            arguments["max_sequence_length"] = preset.runtime.max_sequence_length

        with torch.inference_mode():
            encoded = pipeline.encode_prompt(**arguments)
        if preset.name == "sd15":
            names = ("prompt_embeds", "negative_prompt_embeds")
            expected_count = 2
        elif preset.name == "sdxl-base":
            names = ("prompt_embeds", "negative_prompt_embeds", "pooled_prompt_embeds",
                     "negative_pooled_prompt_embeds")
            expected_count = 4
        elif preset.name == "flux1-schnell":
            # The third value is text_ids, regenerated by FLUX on its execution device.
            names = ("prompt_embeds", "pooled_prompt_embeds")
            expected_count = 3
        else:
            raise ValueError(f"Unsupported CPU conditioning preset: {preset.name}")
        if len(encoded) != expected_count:
            raise RuntimeError(f"Unexpected CPU conditioning result for {preset.name}.")
        tensors = dict(zip(names, encoded))
        if tensors["prompt_embeds"] is None:
            raise RuntimeError("CPU conditioning returned no prompt embeddings.")
        for name, tensor in tensors.items():
            if tensor is not None and (
                tensor.device.type != "cpu" or not torch.isfinite(tensor).all().item()
            ):
                raise RuntimeError(f"CPU conditioning {name} is not finite CPU data.")
        return CpuConditioning(tensors, {
            "enabled": True,
            "execution_device": "cpu",
            "dtype": str(cpu_dtype),
            "components": [name for name, _ in encoders],
            "shapes": {name: None if tensor is None else list(tensor.shape)
                       for name, tensor in tensors.items()},
        })
    finally:
        # SD/SDXL encode_prompt uses the encoder's dtype even when embeddings are
        # supplied. Restore the accelerator storage dtype before installing hooks.
        for encoder, dtype, parameters, buffers in original_storage:
            encoder.to(device="cpu", dtype=dtype)
            for name, tensor in parameters.items():
                encoder.get_parameter(name).data = tensor
            for name, tensor in buffers.items():
                encoder.get_buffer(name).data = tensor
