"""Explicit CPU text encoding before Diffusers installs accelerator/offload hooks."""

from __future__ import annotations

from dataclasses import dataclass
from itertools import chain
from typing import Any

from encoder_compatibility import clip_skip_compatibility
from presets import PipelinePreset


@dataclass(frozen=True)
class CpuConditioning:
    tensors: dict[str, Any]
    metadata: dict[str, Any]

    def for_device(self, device: str, dtype: Any) -> dict[str, Any]:
        # FLUX does not move user-provided embeddings internally. Explicitly move
        # all four SDXL conditioning tensors as well, including pooled negatives.
        return {
            name: None if tensor is None else tensor.to(device=device, dtype=dtype)
            for name, tensor in self.tensors.items()
        }


def encode_cpu_prompt(
    pipeline: Any, preset: PipelinePreset, args: Any, torch: Any
) -> CpuConditioning:
    encoders = [
        (name, getattr(pipeline, name, None))
        for name, _ in preset.expected_components
        if name in ("text_encoder", "text_encoder_2")
    ]
    for name, encoder in encoders:
        if encoder is None:
            raise RuntimeError(f"CPU conditioning requires {name}.")
        if getattr(encoder, "_hf_hook", None) is not None or encoder.device.type == "meta":
            raise RuntimeError("CPU conditioning must run before accelerator/offload hooks.")

    original_storage = []
    for _, encoder in encoders:
        dtype = encoder.dtype
        # PEFT adapters and some buffers can have a different storage dtype
        # from the base encoder. Retain those tensors, avoiding a lossy
        # float32 -> float16 -> float32 round trip during restoration.
        mixed_parameters = {
            name: tensor.detach().to(device="cpu")
            for name, tensor in encoder.named_parameters() if tensor.dtype != dtype
        }
        mixed_buffers = {
            name: tensor.detach().to(device="cpu")
            for name, tensor in encoder.named_buffers() if tensor.dtype != dtype
        }
        original_storage.append((encoder, dtype, mixed_parameters, mixed_buffers))
    dtype_name = getattr(args, "cpu_text_dtype", "auto")
    cpu_dtype = getattr(torch, preset.runtime.cpu_dtype if dtype_name == "auto" else dtype_name)
    try:
        for name, encoder in encoders:
            encoder.to(device="cpu", dtype=cpu_dtype)
            if any(tensor.device.type != "cpu"
                   for tensor in chain(encoder.parameters(), encoder.buffers())):
                raise RuntimeError(f"{name} did not move entirely to the CPU.")

        arguments: dict[str, Any] = {
            "prompt": args.prompt,
            "device": "cpu",
            # SD/SDXL repeat externally supplied embeddings in __call__.
            # FLUX does not: expand here and set its call-time multiplier to 1.
            "num_images_per_prompt": (
                getattr(args, "num_images", 1) if preset.family == "flux1-schnell" else 1
            ),
        }
        if preset.family in ("sdxl-base", "flux1-schnell"):
            arguments["prompt_2"] = getattr(args, "prompt_2", None)
        if preset.runtime.passes_negative_prompt:
            arguments["negative_prompt"] = args.negative_prompt
            arguments["do_classifier_free_guidance"] = args.guidance_scale > 1.0
            arguments["clip_skip"] = getattr(args, "clip_skip", None)
            if preset.family == "sdxl-base":
                arguments["negative_prompt_2"] = getattr(args, "negative_prompt_2", None)
        if preset.runtime.max_sequence_length is not None:
            arguments["max_sequence_length"] = getattr(
                args, "max_sequence_length", preset.runtime.max_sequence_length)
        attention_name = "joint_attention_kwargs" if preset.family == "flux1-schnell" else "cross_attention_kwargs"
        attention_options = getattr(args, attention_name, {})
        if "scale" in attention_options:
            arguments["lora_scale"] = attention_options["scale"]

        with torch.inference_mode(), clip_skip_compatibility(
            pipeline, preset, getattr(args, "clip_skip", None)
        ) as clip_compatibility_used:
            encoded = pipeline.encode_prompt(**arguments)
        if preset.family == "sd15":
            names = ("prompt_embeds", "negative_prompt_embeds")
            expected_count = 2
        elif preset.family == "sdxl-base":
            names = ("prompt_embeds", "negative_prompt_embeds", "pooled_prompt_embeds",
                     "negative_pooled_prompt_embeds")
            expected_count = 4
        elif preset.family == "flux1-schnell":
            # The third value is text_ids, regenerated by FLUX on its execution device.
            names = ("prompt_embeds", "pooled_prompt_embeds")
            expected_count = 3
        else:
            raise ValueError(f"Unsupported CPU conditioning preset: {preset.name}")
        if len(encoded) != expected_count:
            raise RuntimeError(f"Unexpected CPU conditioning result for {preset.name}.")
        tensors = dict(zip(names, encoded))
        if preset.family == "flux1-schnell" and getattr(args, "true_cfg_scale", 1.0) > 1.0:
            negative_arguments = {
                **arguments, "prompt": args.negative_prompt,
                "prompt_2": getattr(args, "negative_prompt_2", None),
            }
            with torch.inference_mode():
                negative_encoded = pipeline.encode_prompt(**negative_arguments)
            if len(negative_encoded) != 3:
                raise RuntimeError("Unexpected FLUX negative CPU conditioning result.")
            tensors.update(zip(("negative_prompt_embeds", "negative_pooled_prompt_embeds"), negative_encoded))
        if tensors["prompt_embeds"] is None:
            raise RuntimeError("CPU conditioning returned no prompt embeddings.")
        for name, tensor in tensors.items():
            if tensor is not None and (
                tensor.device.type != "cpu" or not torch.isfinite(tensor).all().item()
            ):
                raise RuntimeError(f"CPU conditioning {name} is not finite CPU data.")
        return CpuConditioning(tensors, {
            "enabled": True,
            "execution_device": "cpu",
            "dtype": str(cpu_dtype),
            "num_images_per_prompt": arguments["num_images_per_prompt"],
            "clip_skip_layout_compatibility": clip_compatibility_used,
            "components": [name for name, _ in encoders],
            "shapes": {name: None if tensor is None else list(tensor.shape)
                       for name, tensor in tensors.items()},
        })
    finally:
        # SD/SDXL encode_prompt uses the encoder's dtype even when embeddings are
        # supplied. Restore the accelerator storage dtype before installing hooks.
        for encoder, dtype, parameters, buffers in original_storage:
            encoder.to(device="cpu", dtype=dtype)
            for name, tensor in parameters.items():
                encoder.get_parameter(name).data = tensor
            for name, tensor in buffers.items():
                encoder.get_buffer(name).data = tensor
